name:                dhall-recursive-json
version:             0.1.0.0
github:              "akshaymankar/dhall-recursive-json"
license:             BSD3
author:              "Akshay Mankar"
maintainer:          "itsakshaymankar@gmail.com"
copyright:           "Akshay Mankar"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/akshaymankar/dhall-recursive-json#readme>

dependencies:
- base >= 4.7 && < 5
- lens-family-core
- dhall
- dhall-json
- text
- transformers
- prettyprinter
- ansi-terminal
- prettyprinter-ansi-terminal
- aeson-pretty
- bytestring
- optparse-applicative
- cborg
- cborg-json
- serialise
- aeson
- dotgen

library:
  source-dirs: src

executables:
  dhall-to-json:
    main:                Main.hs
    source-dirs:         dhall-to-json
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dhall-recursive-json

  dhall:
    main:                Main.hs
    source-dirs:         dhall
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dhall-recursive-json

tests:
  dhall-recursive-json-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
